### ISSUE TITLE
Mix 2.0

### ISSUE THREAD

**Issue by sunscreem** [spatie/dashboard.spatie.be#100]
More of an FYI. I speculatively tried changing to using laravel mix 2.0, and npm was not happy with me about it. Instead of (helpfully) debugging I've been lazy and rolled back to the 0.* release. Just thought you might like the heads up on this one :)

**Comment by sebastiandedeyne** [comment]
Thanks for the heads up! PR'ing a Laravel Mix 2.0 update as we speak in case you'd want to pull in a more recent version :)
