### ISSUE TITLE
weather is not showing because of display:none in css

### ISSUE THREAD

**Issue by vesper8** [spatie/dashboard.spatie.be#106]
I dunno if this is a bug or an oversight.. but it seems weird to me that in the dashboard.blade.php there are values for setting the weather city, but then the weather does not appear even though a call IS being made to yahoo to fetch the weather on an interval

kinda wasted 20 minutes debugging before I realized the fields were simply set to display:none by default in the css

```
.time-weather__time-zone {
    position: absolute;
    bottom: 0;
    left: 0;
    /* display: none; */
    width: 100%;
    color: var(--yellow);
    text-align: center;
    text-transform: uppercase;
    font-size: var(--font-size-xs);
}

.time-weather__date {
    /* display: none; */
    color: var(--gray-light);
    text-transform: uppercase;
    font-size: var(--font-size-xs);
}

.time-weather__weather {
    /* display: none; */
    color: var(--gray-light);
    font-size: var(--font-size-m);
}
```

This should be covered or documented somewhere.. or enabled/disabled through a configuration option.. IMO

**Comment by freekmurze** [comment]
Strange, on our dashboard the weather is displayed perfectly.

> This should be covered or documented somewhere.. or enabled/disabled through a configuration option.. IMO

Keep in mind that we [don't offer any support whatsoever](https://github.com/spatie/dashboard.spatie.be#support) for the code in this repo.

**Comment by vesper8** [comment]
That is weird indeed.. 

And Yes.. I know you've said this before.. that's a bit of a shame however considering how excellent this package is and how excellent your tutorial on using it at the last Laracon

I don't know how many people are actually using it but count me in for one that is now fully invested in using it and extending it with custom components to meet the needs of my dashboard

Which led me to my next question.. which I'm tempted to open an issue for but won't.. is that it would have been great if you had included in the docs a nomenclature to follow for anyone wanting to make and share custom components. For example any components starting with dsb (for dashboard spatie be) could be easily located

What I'm basically saying is that I think this Dashboard would have wings to become a very widely adopted dashboard which would be even more likely if users could easily share their extensions to it in the form of custom components

**Comment by freekmurze** [comment]
We currently have no interested in investing our time in guiding such an effort.

Feel free to fork our dashboard and build out your idea.

**Comment by willemvb** [comment]
To be complete: the extra weather/time properties are hidden on smaller screens, but shown when there is enough room (which is kinda subjective, depending on how your grid is set up):
https://github.com/spatie/dashboard.spatie.be/blob/master/resources/assets/css/components/time-weather.css#L54-L65

I'm thinking about removing these breakpoints and let the weather/time tile overflow instead.

**Comment by vesper8** [comment]
ah I see, that explains it

But it's odd because I was testing it both on my mac's "Packed Pixel" screen which has the resolution of a tablet.. where I could neither see the name of the city or the weather. But I also tested it on my macbook's main screen.. which is a retina screen (15 inch) so the resolution is quite large.. and there I could see the name of the city but still not the weather. I guess you had made it so the weather is only visible on huge resolutions. Anyway I think it's good that you removed the breaks.

Cheers!

**Comment by willemvb** [comment]
Indeed, it was mainly designed for our large TV screen in the office. Updated here f3bf79e8d10489f988a6b28c6b89016fd507d2b3
