### ISSUE TITLE
Installation without artisan?

### ISSUE THREAD

**Issue by m1guelpiedrafita** [spatie/dashboard.spatie.be#11]
Hi!
I have some restrictions in my webserver, so I can't run `php artisan`.
Is there any way to install it without artisan?
Can I do manually what `php artisan install` does?
Also, could it use a MySQL DB instead of a SQLite DB?

**Comment by freekmurze** [comment]
You need to be able to run `php artisan` to execute the artisan tasks the update the data of the widgets.

Please install the project onto a server where you have some more freedom.
