### ISSUE TITLE
Quote not showing

### ISSUE THREAD

**Issue by danijelk** [spatie/dashboard.spatie.be#111]
Not sure if this behaviour is normal, seems to me like the key 'quoted_status' is missing? Or is this just treated as a reply, in which case the 'In reply to' never shows?

![image 2018-06-26 at 12 03 04 pm](https://user-images.githubusercontent.com/580753/41904630-2987790c-7939-11e8-98a8-ac1359d846db.png)

![image 2018-06-26 at 12 04 45 pm](https://user-images.githubusercontent.com/580753/41904665-429e84b2-7939-11e8-8472-e57446a440a4.png)

**Comment by AlexVanderbist** [comment]
I don't think replies ever showed up but I might be wrong. Quoted statuses should still show up.
