### ISSUE TITLE
Adding How To for starting the dashboard locally

### ISSUE THREAD

**Issue by LucitheR** [spatie/dashboard.spatie.be#112]
Hi there, awesome product :)

it would be nice though to elaborate on how to start the dashboard which port etc. 
I read (granted merely skimmed) the laravel docs for infos about that and also webpack/vue but i didn't find anything :( that allows me to start it

that would be a huge help :)

**Comment by freekmurze** [comment]
Hi,

we don't provide any support for the dashboard. In order to use it, you must be familiar with Laravel and Vue.  For a high level overview of how it works, watch this video: https://www.youtube.com/watch?v=jtB_rTh61Zo
