### ISSUE TITLE
RPi?

### ISSUE THREAD

**Issue by m1guelpiedrafita** [spatie/dashboard.spatie.be#12]
Hi!
Every time I try to run the app, It gives me an error:
`SQLSTATE[HY000]: General error: 1 no such table: users (SQL: select * from "users" where "email" = m1guelpiedrafita limit 1)`
I think it is because there is a problem with the database.sqlite file. Could you please share an example database.sqlite?
Thank you!

**Comment by freekmurze** [comment]
An empty sqlite db can be any empty file. Did you run the migrations?

**Comment by m1guelpiedrafita** [comment]
How di I run the migrations?

**Comment by freekmurze** [comment]
To run migrations you can just run `php artisan migrate` at the command line.

**Comment by m1guelpiedrafita** [comment]
Hi!
I solved that but now I have another problem:
`ErrorException in helpers.php line 410:
File css/app.css not defined in asset manifest. (View: /home/u395355350/data/dashboard/resources/views/layouts/master.blade.php) (View: /home/u395355350/data/dashboard/resources/views/layouts/master.blade.php)`
Where is /public/css ?

**Comment by freekmurze** [comment]
Run `npm install` and then `gulp` to compile all the assets.

**Comment by anchepiece** [comment]
I think you need to run gulp to build the assets.

**Comment by m1guelpiedrafita** [comment]
Thanks!
Finally, would it work with [https://www.raspberrypi.org/forums/viewtopic.php?t=19702](https://www.raspberrypi.org/forums/viewtopic.php?t=19702)?

**Comment by freekmurze** [comment]
Can't say for certain, just test it out 😄

**Comment by m1guelpiedrafita** [comment]
But isn't php7 needed?

**Comment by freekmurze** [comment]
PHP 7 is needed, if your distro doesn't support that, it's already game over.
