### ISSUE TITLE
single tile uses fullscreen

### ISSUE THREAD

**Issue by mybigman** [spatie/dashboard.spatie.be#128]
Placing a single tile on the dashboard using a range say a1:a4 always uses all available space.

How can one occupy that upper left corner?

I tried adding columns and rows however this seems like it was removed?

**Comment by freekmurze** [comment]
The lastest version of the dashboard determines the number of rows and columns automatically. If you only have one tile, it will use all space. If you need to have some open space on your dashboard. You need to create a tile for that.
