### ISSUE TITLE
Error SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dashboard.users' on setup

### ISSUE THREAD

**Issue by gjportegies** [spatie/dashboard.spatie.be#129]
At the end of running composer install I'm getting the following error:

```
Generating autoload files> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In Connection.php line 664:
                                                                               
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dashboard.users'  
   doesn't exist (SQL: select * from `users` limit 1)                          
                                                                               

In Connection.php line 326:
                                                                               
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dashboard.users'  
   doesn't exist 
```

**Comment by freekmurze** [comment]
Try running the migrations with `php artisan migrate`.

**Comment by gjportegies** [comment]
@freekmurze that's not possible because it's giving the same error. It already appeared after running composer install after just cloning this project. So it's not even possible the generate the key.

Are there any required settings for the .env besides the database credentials?

**Comment by freekmurze** [comment]
> that's not possible because it's giving the same error.
Feel free send a PR that fixes this.

> Are there any required settings for the .env besides the database credentials?
I don't think so.

**Comment by gjportegies** [comment]
@freekmurze it's caused by the AuthServiceProvider.php I've commented the following lines:
```
if ($user = User::first()) {
    auth()->login($user);
}
```

User table does not exist at this point when first setting up the project.
