### ISSUE TITLE
example configuration files.

### ISSUE THREAD

**Issue by illuminate3** [spatie/dashboard.spatie.be#13]
I'm having trouble with basically every config to make this work.

I do have pusher working though.

Would you include your config files? And examples of what your are using for the github data?

Thanks!

**Comment by freekmurze** [comment]
We won't include our own `.env` because that contains our own account keys (this is sensitive info). There is however `.env.example` file you can take a look at. Copy that file to `.env` and fill it with your own account keys.

**Comment by illuminate3** [comment]
I get that and wouldn't ask your secret keys.

I read your blog several times, I tried setting this up about a month ago but ended up with the same problems. I came back today and tried again with a fresh hope but ran into the same problems.

I added my GOOGLE_CALENDAR_ID which works with another app but with yours I get nothing in the upcoming box.

there is GITHUB_FILES but when I point to one file on github it doesn't work. what is the format for this setting? Are you just using a simple markup file for each dev person?

Thanks

**Comment by freekmurze** [comment]
For the GitHub files we have a repo containing one `.md` file per person. If The Beatles worked at Spatie this would be the value in the `.env` file

```
GITHUB_FILES=john,paul,george,ringo
```

If you're getting no exception message from the Google Calendar functionality there's nothing to do but trying to debug this yourself.

**Comment by seandelaney** [comment]
> For the GitHub files we have a repo containing one .md file per person.

Just an empty repo containing `.md` files or is this repo for a specific project?

Is there an example `.md` file?

I'm also trying to get the dashboard working.

Thanks

**Comment by michdess** [comment]
@seandelaney 

You can call the repo whatever you want you'll just need to update the command in app/Console/Components/Tasks/FetchTasks.php

`return $gitHub->fetchFileContent('spatie', 'tasks', "{$fileName}.md", 'master');`

Just replace spatie with your username, and create a tasks repo or change that to the name you want and make sure your filenames match up with your .env file and you should be good to go.

Hope that helps!
