### ISSUE TITLE
Tweets are not showing up

### ISSUE THREAD

**Issue by jetwes** [spatie/dashboard.spatie.be#133]
Everything worked fine, then suddenly the tweet tile is empty and new tweets aren't shown.
If i send a fake tweet i can see this error in the console
`https://pbs.twimg.com/profile_images/613846262383652864/3UKkvJFq_normal.jpg`

any guesses?

**Comment by jetwes** [comment]
![image](https://user-images.githubusercontent.com/1346373/50232933-962b6880-03b2-11e9-8898-7eb246198ed5.png)

**Comment by m1guelpf** [comment]
@freekmurze did you change your Twitter avatar? 😄

**Comment by jetwes** [comment]
just for the record - tweets are back - just like they are gone - without any action ...
