### ISSUE TITLE
Dashboard hangs every morning

### ISSUE THREAD

**Issue by freekmurze** [spatie/dashboard.spatie.be#135]
Often the dashboard is broken when it starts up on our raspberry pi. I suspect something goes wrong when switching from dark to light mode, but not sure.

We should connect remotely to the screen of the raspberry pi and check the console if there are any JavaScript errors there.

**Comment by AdrianMrn** [comment]
Iirc, this was an issue with the csrf-token expiring, was fixed by someone else.
