### ISSUE TITLE
Error in parameters naming in .env.example

### ISSUE THREAD

**Issue by marioene** [spatie/dashboard.spatie.be#136]
Hi,

First, great demo! You are building amazing packages! 

A little error in env.example file (if we have to respect parameters naming from config/broadcasting.php):

At line 44, `PUSHER_KEY=` should be `PUSHER_APP_KEY=`

At line 45, `PUSHER_SECRET=` should be `PUSHER_APP_SECRET=`

**Comment by freekmurze** [comment]
I'll fix this. If you see another misnaming, feel free to send a PR 👍
