### ISSUE TITLE
i can't install this project

### ISSUE THREAD

**Issue by MrKriKri** [spatie/dashboard.spatie.be#137]
first i do when i clone this project 
**composer install**
and i have :

> @php artisan package:discover

In Connection.php line 664:

  Database (C:\dashboard.spatie\database\database.sqlite) does not exist. (SQL: select * from sqlite_master where typ
  e = 'table' and name = users)

In SQLiteConnector.php line 34:

  Database (C:\dashboard.spatie\database\database.sqlite) does not exist.

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

**Comment by freekmurze** [comment]
We don't give support on this repo.

If you feel that there's anything that can improved, feel free to send a PR.

**Comment by urjaramaniVC** [comment]
> first i do when i clone this project
> **composer install**
> and i have :
> 
> > @php artisan package:discover
> 
> In Connection.php line 664:
> 
> Database (C:\dashboard.spatie\database\database.sqlite) does not exist. (SQL: select * from sqlite_master where typ
> e = 'table' and name = users)
> 
> In SQLiteConnector.php line 34:
> 
> Database (C:\dashboard.spatie\database\database.sqlite) does not exist.
> 
> Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

I also got the same issue :(

**Comment by LunarDevelopment** [comment]
From the root of your project just run the following CLI command (or make the file manually)

```
$ touch database/database.sqlite 
```

**Comment by meduzen** [comment]
Also, [Comment the auth check](https://github.com/spatie/dashboard.spatie.be/issues/129#issuecomment-445777227) in the _AuthServiceProvider_. Run everything needed, then uncomment it.
