### ISSUE TITLE
Pusher not pushing or app not registering events? 

### ISSUE THREAD

**Issue by LunarDevelopment** [spatie/dashboard.spatie.be#142]
Hola, 

I know this is a generic help and not an issue with the repo but I was hoping for a bit of help on getting pusher working with the unedited install (other than .env pusher details)

I can't seem to get a message from the `php artisan dashboard:update` commands to the app. 

Got the following running in CLIs (OS X):
`php artisan serve`
`php artisan websockets:serve`
`php artisan queue:listen`
`php artisan queue:work` (just in case.. )

Then running any of the artisan dashboard commands shows up nothing on the pusher debug other than sporadic things like : 
```
SUBSCRIBED  262032.937786  Channel: private-dashboard  
and

DISCONNECTION    262113.619137    Channels: private-dashboard, Lifetime: 35.786499902s

CONNECTION 262261.180247 Origin:
```
I've got no webhook url configured in pusher and at no point have I put in pusher my local host ip and port (I'm assuming it just pushes to listeners who've subscribed so no need)

The JS/ Echo seems to be polling to try and get pusher shit but always comes back with no content: 
```
Request URL: http://sock119-mt1.pusher.com/pusher/app/12847e1e95f8290e9082/914/gejhiet4/xhr_send?t=1557933153736&n=2
Request Method: OPTIONS
Status Code: 204 No Content

Request URL: http://sock119-mt1.pusher.com/pusher/app/12847e1e95f8290e9082/914/gejhiet4/xhr_send?t=1557933153736&n=2
Request Method: POST
Status Code: 204 No Content
```

**Comment by freekmurze** [comment]
Sorry, we currently have no time for support on this repo.
