### ISSUE TITLE
Is the tile content searchable ?

### ISSUE THREAD

**Issue by ronlinet** [spatie/dashboard.spatie.be#147]
Is that real time content searchable ? Given the fact that the tiles are not populated from a db ..

**Comment by freekmurze** [comment]
I don't know what you mean by searchable. Could you clarify that?

**Comment by ronlinet** [comment]
https://www.w3schools.com/howto/howto_js_filter_lists.asp

**Comment by ronlinet** [comment]
It is a pretty quick hack and it would be a great feature

**Comment by freekmurze** [comment]
I really don't know what you're trying to achieve. You can manually create tiles and let them behave to your heart's content.
