### ISSUE TITLE
path issue

### ISSUE THREAD

**Issue by mithauae** [spatie/dashboard.spatie.be#169]
( ! ) Warning: require(C:\wamp64\www\spatie\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\wamp64\www\spatie\bootstrap\autoload.php on line 17

( ! ) Fatal error: require(): Failed opening required 'C:\wamp64\www\spatie\bootstrap/../vendor/autoload.php' (include_path='.;C:\php\pear') in C:\wamp64\www\spatie\bootstrap\autoload.php on line 17

**Comment by freekmurze** [comment]
Tests prove that the package is working correctly. This is probably caused by something for your specific project.

**Comment by mithauae** [comment]
the following error found while composer install

 1   [internal]:0
      Spatie\OhDearUptimeTile\OhDearUptimeStore::__construct()

  2   [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(Spatie\OhDearUptimeTile\OhDearUptimeTileServiceProvider))
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
