### ISSUE TITLE
not working for me :\

### ISSUE THREAD

**Issue by marcostimm** [spatie/dashboard.spatie.be#2]
Missing argument 1 for Illuminate\Support\Manager::createDriver(), called in /dash/vendor/laravel/framework/src/Illuminate/Support/Manager.php on line 87 and defined

**Comment by freekmurze** [comment]
We do not provide support for this repo. 

It seems that an .env value is not properly configured.

I'll soon publish a blog post with some general pointers on how to setup a dashboard.

**Comment by marcostimm** [comment]
thanks!

**Comment by mauritzbotha** [comment]
Adding "file" to the last three settings in the .env file fixes it:
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=file
