### ISSUE TITLE
Not receiving events

### ISSUE THREAD

**Issue by janhenckens** [spatie/dashboard.spatie.be#25]
Hey Spatie, 

Thanks for this really neat dashboard! I'm trying to get it up & running so we can customise it for use at our office. But I'm running into a couple of issues:

I can see my events arriving on the Pusher debug console, but it looks like my dashboard isn't receiving them. First time using Echo and Pusher and I'm not sure where to start debugging this.

Thanks for your feedback
Jan

**Comment by freekmurze** [comment]
Open up your console. Do you see errors there? 

Any questions regarding setting up Laravel Echo should be asked at the [their repo](https://github.com/laravel/echo).

**Comment by janhenckens** [comment]
No console errors, no errors in the Vue debug extension either.

**Comment by freekmurze** [comment]
If you find the solution, report back here. You solution might help future users.

**Comment by stelgenhof** [comment]
@janhenckens Have you checked that the scheduler is running?
