### ISSUE TITLE
Composer.lock

### ISSUE THREAD

**Issue by stelgenhof** [spatie/dashboard.spatie.be#28]
Hi Spatie guys!

I noticed you have included the composer.lock file in the git repository. Any particular reason for this? I believe ideally the lock file shouldn't be in the git repos :)

Thanks for the wonderful dashboard!

**Comment by freekmurze** [comment]
Hi Sacha,

hope you're doing well at the other side of the planet 😄 

Well, if this were a normal open source project repo a `composer.lock` file shouldn't be here. But this repo contains the actual source code for our dashboard. We're deploying from this repo. So we need that `composer.lock` file to ensure the right versions of the package are being used on the server.

**Comment by stelgenhof** [comment]
Doing super here! Ok, considering that it makes sense :)
