### ISSUE TITLE
Elixir NPM

### ISSUE THREAD

**Issue by necrogami** [spatie/dashboard.spatie.be#35]
Elixir has been moved to NPM could this potentially get updated to reflect?

**Comment by sebastiandedeyne** [comment]
I read something about Elixir requiring npm for now due to some issue with yarn, do you have any concrete information on it?

Currently using Elixir with yarn and haven't had any issues yet... (and I'd really prefer to keep yarn)

**Comment by necrogami** [comment]
yeah documentation still says to use gulp which breaks because it can't find elixir or elixir vue components

**Comment by sebastiandedeyne** [comment]
I'm using Elixir in about 3 projects now with yarn and haven't seen any issues. If an error pops up I'll look into this.

Gonna close this for now as we're going to keep using yarn for now.
