### ISSUE TITLE
Rasbian

### ISSUE THREAD

**Issue by jonwhittlestone** [spatie/dashboard.spatie.be#5]
Hi,

Looks like a really nice project, would you also be able to share the code/bash script you've used to display on the TV with the raspberry pi / chromium?

Thanks!

Jon via Laravel News

**Comment by djekl** [comment]
Opening a browser is explained here on the Raspberry Projects site - [Autorun browser on startup - Raspberry Pi Projects](http://www.raspberry-projects.com/pi/pi-operating-systems/raspbian/gui/auto-run-browser-on-startup)

**Comment by jonwhittlestone** [comment]
Thx

**Comment by jonwhittlestone** [comment]
Thx
