### ISSUE TITLE
The Mix manifest does not exist after updating Spatie dashboard

### ISSUE THREAD

**Issue by ianrussel** [spatie/dashboard.spatie.be#52]
I updated my spatie dashboard by running
   
           git pull
           composer update
          rm -rf  node_modules
         npm install

Now my spatie dashboard ain't running

The error shows 

> The Mix manifest does not exist

**Comment by freekmurze** [comment]
This repo doesn't follow semver at all. Breaking changes may be introduced all the time. Unless you don't mind tinkering with the code to get it up and running after every update, it's best not to perform `git pull`.

That being said, we switched to Laravel mix for the compilation of assets. You might get it running again by performing `yarn run dev` to generate the assets.
