### ISSUE TITLE
Insufficient error handling on the server

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/dashboard.spatie.be#54]
When a task goes wrong, the dashboard gets stuck in a no-connection state.

Concrete examples of situations that kill the dashboard:

- When a task is fetched for a user that doesn't have a task list
- When Buienradar is down (seems to happen every day around noon)

If a task errors, it shouldn't affect the heartbeat.

**Comment by freekmurze** [comment]
@AlexVanderbist could you take a look on how this can be fixed?

**Comment by morloderex** [comment]
@freekmurze @sebastiandedeyne Just curious couldn't this be fixed just by running the heartbeat outside of the schedule:run artisan command? 
By just having a separate cron job setting for just this one command?

**Comment by freekmurze** [comment]
That's a good tip @morloderex 

But in an ideal world, Laravel should make sure that every command gets a change to run even if the another one fails in the same run. Will look into it.
