### ISSUE TITLE
Moving tiles

### ISSUE THREAD

**Issue by morloderex** [spatie/dashboard.spatie.be#56]
Hello @spatie 

You have a great starting point in your creation I've managed to build upon your dashboard to make it my own.. So much THANK YOU for the grid system it's so nice and easy to use! :)

Now I have a question/help wanted thing: 
I want to make the dashboard more appealing to people watching it so I thought that I would implement a mechanism to make the tiles move around e.g (a tile that is the same size and is in the position next to another tile can switch places within a time interval or even be totally hidden while another tile is shown)

If you also want such a feature we could help each other creating it as my Vue expertise drops a bit here. 

Let me know what you think! :)

**Comment by freekmurze** [comment]
We currently have no need for such functionality, so we probably won't invest time in this. But of course, feel free to fork our code and do whatever you want with it 😄

**Comment by morloderex** [comment]
Okay let me know if times change.. :)
