### ISSUE TITLE
no content?

### ISSUE THREAD

**Issue by hzz520** [spatie/dashboard.spatie.be#61]
![b38a6da1-1151-48c7-9343-420e3348ac3b](https://cloud.githubusercontent.com/assets/20789167/25943390/4b3b87ce-3672-11e7-8dce-f73637727471.png)

**Comment by freekmurze** [comment]
That's normal, you'll need to setup your own tiles and sources where data is being pulled in.

This repo does not contain an empty template for you to start with, but the soure code of our actual dashboard.

Please not that we don't give support on this dashboard.
