### ISSUE TITLE
GitHub contributors is fluctuating

### ISSUE THREAD

**Issue by freekmurze** [spatie/dashboard.spatie.be#67]
The number of contributors sometimes goes down. Seem highly unlikely that this is correct.

**Comment by freekmurze** [comment]
When running `dashboard:fetch-github-totals` a few times in succession, the numer of contributors varies. I'm thinking this is a problem with the GitHub API itself.

**Comment by sebastiandedeyne** [comment]
Is this in our control? Otherwise might as well close this.

**Comment by freekmurze** [comment]
Nope. Closing...
