### ISSUE TITLE
readme.md explain

### ISSUE THREAD

**Issue by m-bosch** [spatie/dashboard.spatie.be#73]
in the support part of the readme:

```We do not follow semver for this project and do not provide support whatsoever.```

Semver? Cant trace that word back to something logical. Perhaps my fault?

**Comment by m1guelpf** [comment]
@m-bosch [Semantic Versioning](http://semver.org/) Remember to RTFW :smile:

**Comment by freekmurze** [comment]
Added a link to http://semver.org/ in the readme.
