### ISSUE TITLE
Thumbs up emoji is not being displayed correctly

### ISSUE THREAD

**Issue by freekmurze** [spatie/dashboard.spatie.be#74]
That questionmark should be "👍 "

![screen shot 2017-06-12 at 15 36 18](https://user-images.githubusercontent.com/483853/27036374-f6c31d0c-4f84-11e7-80ee-fa08ee9f24d2.png)

**Comment by freekmurze** [comment]
🦄

**Comment by willemvb** [comment]
This had to do with the `display_text_range` of a tweet, in combination with Unicode surrogate pairs for emojis. 
Just getting `substring(0,1)` of the text broke this single emoji in half. 
I also added emojis in author names.
