### ISSUE TITLE
Avoid fetching packagist stats if vendor is not configured

### ISSUE THREAD

**Issue by Seldaek** [spatie/dashboard.spatie.be#75]
If services.packagist.vendor is null or empty then https://github.com/spatie/dashboard.spatie.be/blob/0cd2647fc7127b52602d704e0a52a8d7014ed2b1/app/Console/Components/Packagist/FetchTotals.php#L20 will fetch the entire list of packagist packages, and then proceed to fetch them all via the API. This resulted in someone using your dashboard to do hourly updates of the entire db (143'000 packages * 24h = 3'432'000 requests per day or an equivalent of ~40 requests per second done to our API).

Maybe it should just skip this or error loudly if the config is not valid.

Defensive programming++ ;)

**Comment by freekmurze** [comment]
Thanks for bringing this to my attention, my apologies for the troubles caused.

I've tagged [a new release of the underlying api package](https://github.com/spatie/packagist-api/releases/tag/1.0.1). This will throw an exception when passing an empty value to `getPackagesByVendor`.

**Comment by freekmurze** [comment]
Hopefully the culprit will pull in the fix: https://twitter.com/freekmurze/status/874646032243724288

**Comment by Seldaek** [comment]
Yeah I was talking to them (never would have found the cause otherwise) so I think they fixed their config in the meantime. Thanks

**Comment by bbashy** [comment]
I had the dashboard running but only half configured. `PACKAGIST_VENDOR=` was blank so it was just calling all.

I worked with @Seldaek to resolve it quickly. Was so confused with why something would be doing this on our server! I've since added a vendor and disabled schedules that I don't need running.
