### ISSUE TITLE
resize column like 1.5

### ISSUE THREAD

**Issue by ianrussel** [spatie/dashboard.spatie.be#78]
I am currently using this amazing dashboard, I have just have one question for the column(size). Does it possible to add column size equivalent to 1 and 1  half, like

         <admin-file file-name="Admin" grid="a1:b1.5"></admin-file>//I mean 2 and a half column equivalent
        <feedback-file file-name="Feedback" grid="b1:c1"></feedback-file>

I don't know how to it in __grid.scss file

Thanks

**Comment by freekmurze** [comment]
Halves are not supported. If you want more fine grained control, just double the amount of rows an columns and use ranges for all the components.

In the latest version of the dashboard the amount of columns and rows can be modified [here](https://github.com/spatie/dashboard.spatie.be/blob/bca5965/resources/views/dashboard.blade.php#L7).

**Comment by ianrussel** [comment]
Many thans @freekmurze
