### ISSUE TITLE
Question - Can a color be passed to the Tasks Component

### ISSUE THREAD

**Issue by jongravois** [spatie/dashboard.spatie.be#79]
I am loving your dashboard. I cloned it to check it out.  I modifed the template of Tasks. vue as

```
<tile :position="position" modifiers="overflow green">
```

and all the tasks panels turned green .... cool. However, I was wondering if there is a way to modify

```
<tasks team-member="alex" position="c2"></tasks>
```

in dashboard.blade.php to allow for different colors for each worker. Our thought is to use a green, yellow, orange, red scale to represent the worker to deadline ratio and need to be able to change panels individually.

This is a great dashboard and tool! Thanks for sharing!

**Comment by willemvb** [comment]
Hey Jonathan,
Glad you like it! There is no way at this time do this out of the box. 
A workaround is to add a CSS class directly to the HTML component.
```
<tasks … class="tile--green"></tasks>
```
You can use the classes from `tile.css` and add colors there.

The clean way would require some Vue tweaking. You could add the modifier property to the HTML
```
<tasks … modifier="overflow green"></tasks>
```
and then pass this property in `Tasks.vue` to the actual tile. The script should be adapted to accept the new property `modifiers` of the task and bind it to the `modifiers` prop of a tile.
```
<template>
    <tile … :modifiers="modifiers">
        …
    </tile>
</template>

<script>
   …
    export default {

        …
        props: […, 'modifiers'],
```

Hope this helps!
