### ISSUE TITLE
Google Calendar Config 'file not found' Exception

### ISSUE THREAD

**Issue by JoshMountain** [spatie/dashboard.spatie.be#84]
I've placed a valid public calendar ID into my env's `GOOGLE_CALENDAR_ID` however when I run `php artisan dashboard:fetch-calendar-events` I get the following error:

```
[2017-09-06 01:47:36] local.ERROR: file does not exist {"exception":"[object] (InvalidArgumentException(code: 0): file does not exist at /home/vagrant/Code/dashboard/vendor/google/apiclient/src/Google/Client.php:849)
```

**Comment by sfavorite** [comment]
Josh,

Did you setup a google calendar api for the dashboard? It appears you don't have a client_secret.json file (/storage/app/laravel-google-calendar/client_secret.json). You can setup the api and get the information for the client_secret.json file at [Google Developers](https://console.developers.google.com).

FYI: I am not a spatie developer just a fan of the dashboard but hopefully my information above helps you.

**Comment by xahy** [comment]
Check the documentation of [spatie/laravel-google-calendar](https://github.com/spatie/laravel-google-calendar#how-to-obtain-the-credentials-to-communicate-with-google-calendar)

You will see a step by step example of how to generate the json file
