### ISSUE TITLE
Add npm stats tile

### ISSUE THREAD

**Issue by freekmurze** [spatie/dashboard.spatie.be#86]
Currently we have a tile to display stats for all our PHP stuff on Composer. It would be nice to have a tile with statistics for all our JS stuff on NPM.

**Comment by manniL** [comment]
You could use the [npm-stats-api package](https://github.com/Developmint/npm-stats-api) that appeared magically. 🤔  But I guess I'll provide a PR if I have the time in the next days :)

**Comment by manniL** [comment]
The only problem is that scoped packages (like @spatie/blender-media) are not supported in bulk calls, meaning that you'd need single calls for half of your packages. 
Furthermore, you need individual calls for daily/monthly/total, even when using bulk.

So it might be a little time-intensive in comparison to the packagist API calls.

**Comment by freekmurze** [comment]
We'll handle this further in #89
