### ISSUE TITLE
phpinfo() in app.js?

### ISSUE THREAD

**Issue by markuskoehler** [spatie/dashboard.spatie.be#92]
Hey,

I have a very strange issue after following the installation steps. after executing "yarn run dev" and even "npm run dev", my app.js contains - when opened in the browser - a full and valid phpinfo() output... when I view it in PHPStorm, it shows valid webpack content, but how can it be that my browser sees phpinfo() executed inside the app.js?? Any idea on this?

**Comment by freekmurze** [comment]
I'm thinking this is something related to your setup as our code doesn't contain a `phpinfo` call.
