### ISSUE TITLE
laravel/echo namespaces issue handling ?

### ISSUE THREAD

**Issue by ntavelis** [spatie/dashboard.spatie.be#95]
Hello, 

first of all I love your dashboard 😄.
It seems that there is a known issue in the community regarding the namespaces and the event names.
[issue](https://github.com/laravel/echo/issues/119#issuecomment-317627591). In a nutshell the issue is that the client can not properly listen for events that are namespaced. e.g.

`
 Echo.private('dashboard').listen('.app.events.Twitter.mentioned', (e) => {// do smt});
`
The above code wont trigger an event in the client's side, even thought the laravel docs clearly suggest that it will. I have experienced this issue and the solution is to explicitly specify the event's name.

Event class:
`
public function broadcastAs()
    {
        return 'Mentioned';
    }
`
and then in the client.
`
Echo.private('dashboard').listen('Mentioned', (e) => {// do smt});
`

If you are interested in this fix I can open a pull request. 

Thanks

**Comment by freekmurze** [comment]
Sure, send a PR.
